version: "3.8"

services:

   qbittorrent:
      image: lscr.io/linuxserver/qbittorrent:latest
      container_name: qbittorrent
      env_file:
         - .env
      environment:
         WEBUI_PORT: 8080
      volumes:
         - ./config:/config
         - ./downloads:/downloads
      ports:
         - 6881:6881
         - 6881:6881/udp
         - 8080:8080
      restart: unless-stopped

   ygg-rss-proxy:
      image: ghcr.io/jbesclapez/ygg-rss-proxy:latest
      container_name: ygg-rss-proxy
      ports:
         - 8081:8080
      env_file:
         - .env
      environment:
         # Override specific values for containerized environment
         FLARESOLVERR_HOST: flaresolverr
         RSS_HOST: ygg-rss-proxy
      volumes:
         - ./config:/app/config
      restart: unless-stopped
      depends_on:
         - flaresolverr

   flaresolverr:
      image: ghcr.io/flaresolverr/flaresolverr:latest
      container_name: flaresolverr
      env_file:
         - .env
      environment:
         CAPTCHA_SOLVER: none
      expose:
         - 8191
      restart: unless-stopped